//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_Thu_VienEntities : DbContext
    {
        public QL_Thu_VienEntities()
            : base("name=QL_Thu_VienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_chitietphieu> tbl_chitietphieu { get; set; }
        public virtual DbSet<tbl_docgia> tbl_docgia { get; set; }
        public virtual DbSet<tbl_linhvuc> tbl_linhvuc { get; set; }
        public virtual DbSet<tbl_nhanvien> tbl_nhanvien { get; set; }
        public virtual DbSet<tbl_nxb> tbl_nxb { get; set; }
        public virtual DbSet<tbl_phieumuon_tra> tbl_phieumuon_tra { get; set; }
        public virtual DbSet<tbl_sach> tbl_sach { get; set; }
        public virtual DbSet<tbl_tacgia> tbl_tacgia { get; set; }
        public virtual DbSet<tbl_xuphat> tbl_xuphat { get; set; }
    }
}
