//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_quahan_view
    {
        public int madg { get; set; }
        public string tendg { get; set; }
        public string ngaysinh { get; set; }
        public string gioitinh { get; set; }
        public string lop { get; set; }
        public string diachi { get; set; }
        public string email { get; set; }
        public string ngaymuon { get; set; }
        public string ngaytra { get; set; }
    }
}
