//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_so_luong_sach_view
    {
        public int masach { get; set; }
        public string tensach { get; set; }
        public Nullable<int> manxb { get; set; }
        public Nullable<int> malv { get; set; }
        public Nullable<int> sotrang { get; set; }
        public Nullable<int> soluonghientai { get; set; }
        public Nullable<int> soluongbandau { get; set; }
        public string ngaynhap { get; set; }
    }
}
