//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sachsaphet_view
    {
        public int masach { get; set; }
        public string tensach { get; set; }
        public string tenlinhvuc { get; set; }
        public string tennxb { get; set; }
        public Nullable<int> soluonghientai { get; set; }
        public string ngaynhap { get; set; }
    }
}
