//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_chitietphieu
    {
        public int sophieumuon { get; set; }
        public int masach { get; set; }
        public string trangthaisach { get; set; }
    
        public virtual tbl_phieumuon_tra tbl_phieumuon_tra { get; set; }
        public virtual tbl_sach tbl_sach { get; set; }
    }
}
