//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_xuphat
    {
        public int maphat { get; set; }
        public string loaiphat { get; set; }
        public Nullable<long> giatien { get; set; }
    }
}
