//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_phieumuon_tra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_phieumuon_tra()
        {
            this.tbl_chitietphieu = new HashSet<tbl_chitietphieu>();
        }
    
        public int sophieumuon { get; set; }
        public Nullable<int> madg { get; set; }
        public Nullable<int> manv { get; set; }
        public string ngaymuon { get; set; }
        public string ngaytra { get; set; }
        public Nullable<bool> xacnhantra { get; set; }
        public string ghichu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_chitietphieu> tbl_chitietphieu { get; set; }
        public virtual tbl_docgia tbl_docgia { get; set; }
        public virtual tbl_nhanvien tbl_nhanvien { get; set; }
    }
}
